### ISSUE TITLE
Fix loop joint

### ISSUE THREAD

**Issue by nyxrobotics** [sbgisen/xarm_ros#11]
**Summary**
Fix incorrect behavior of loop joint and mimic joint.
The sdf parser and gazebo plugin seem to be the cause.
Fix xacro to work properly with the latest version.
The cause is unknown and may occur in the future.

**Comment by jsupratman13** [comment]
Probably due to ROS version. The converted sdf (from xacro) version is different depending on which ROS you are using. For ROS noetic, sdf version is probably 1.7
