### ISSUE TITLE
unstable PID parameters for Gazebo

### ISSUE THREAD

**Issue by nyxrobotics** [sbgisen/xarm_ros#3]
Reference https://github.com/xArm-Developer/xarm_ros/commit/d956104f6cb51537db73218cbbbdfa7a51444939
**Summery**
The arm runs out of control when the PID gain is set in the Gazebo simulator. This problem needs to be solved.

If the PID gain is not set, the arm does not perform physical operations of force.
If it grabs an object, it grabs it with infinite force. If it hits a wall, it will bite into the wall and explode.

**Comment by nyxrobotics** [comment]
~~When PID is set, it does not work because pi is not set.
When PID is not set, it works. Probably because physics operations are not performed.~~
-> It was a mistake.
https://github.com/sbgisen/xarm_ros/blob/76de6e39e6ab8fb9358081bfce7fef3bebf99394/xarm_description/urdf/xarm7.urdf.xacro#L9-L17
https://github.com/sbgisen/xarm_ros/blob/76de6e39e6ab8fb9358081bfce7fef3bebf99394/xarm_description/urdf/xarm7_robot_macro.xacro#L38-L46

**Comment by nyxrobotics** [comment]
The physical location of the joint is incorrect.
If this is not corrected, the physics of the force will not be correct
![Screenshot from 2022-04-19 22-18-16](https://user-images.githubusercontent.com/19720932/164013052-568233df-0b12-4045-8cf8-186e01c43599.png)

Should be as below

![Screenshot from 2022-04-19 22-24-31](https://user-images.githubusercontent.com/19720932/164013991-55dd6b08-af38-4d57-b20e-bb8f2d067f21.png)

**Comment by nyxrobotics** [comment]
implicitSpringDamping should be enabled for simulating joint damping:
Reference: https://answers.ros.org/question/288237/robot-arm-is-broken-link-by-link-in-gazebo/
https://github.com/sbgisen/xarm_ros/blob/76de6e39e6ab8fb9358081bfce7fef3bebf99394/xarm_description/urdf/xarm7.urdf.xacro#L124-L126

**Comment by nyxrobotics** [comment]
Fix joint torque
Reference: https://forum.ufactory.cc/t/maximum-torque-value-xarm-5-6-7/2952/2

**Comment by nyxrobotics** [comment]
The range of motion of the joints does not match between the Gazebo model and the controller.
Robot joints suddenly rotate in the Gazebo environment.

**Comment by Tacha-S** [comment]
xarm7 joint range limit
![Screenshot from 2022-04-20 17-47-28](https://user-images.githubusercontent.com/13605820/164189743-dcf0d002-7bc9-4418-94e6-e2a6fe07ebbe.png)

**Comment by nyxrobotics** [comment]
When using Gazebo for PID control of joints with a range of motion greater than one revolution, gazebo_ros_pkgs must be modified.
https://github.com/sbgisen/gazebo_ros_pkgs/tree/feature/multi_turn_joint
